### ISSUE TITLE
Travis failures

### ISSUE THREAD

**Issue by jrfnl** [jcchavezs/cmb2-conditionals#15]
Just wondering what you intended to test via travis as the current script is failing badly.

Also, you are cloning https://github.com/Seravo/wordpress-test-template which is an out-of-date fork of https://github.com/Koodimonni/wordpress-test-template
The travis script might start working again if you switch to the original repo.

**Comment by jcchavezs** [comment]
Thank you @jrfnl. I just fixed it.

**Comment by jrfnl** [comment]
Unfortunately this didn't fix it.
If you like, I'll send in a PR to replace the travis script with a completely different one which will test against PHP parse errors, js errors, js code style and PHP code style.
